name: template_workflow
display_name: "Template Workflow"
description: "A template for creating new workflows"
version: "1.0.0"
icon: "⚡"
color: "#6366f1"

triggers:
  - type: manual
    description: "Manual trigger"

settings: []

agents:
  cards_dir: agents/

tags:
  - new
