name: bank_to_ynab
strategy: sequential

steps:
  - name: format_parser_prompt
    type: function
    ref: workflows.bank_to_ynab.steps.format_parser_prompt

  - name: email_parser
    type: agent
    ref: workflows.bank_to_ynab.agents.email_parser.create_email_parser

  - name: match_account
    type: function
    ref: workflows.bank_to_ynab.steps.match_account

  - name: format_researcher_input
    type: function
    ref: workflows.bank_to_ynab.steps.format_researcher_input

  - name: researcher
    type: agent
    ref: workflows.bank_to_ynab.agents.researcher.create_researcher

  - name: format_categorizer_input
    type: function
    ref: workflows.bank_to_ynab.steps.format_categorizer_input

  - name: categorizer
    type: agent
    ref: workflows.bank_to_ynab.agents.categorizer.create_categorizer

  - name: synthesize_transaction
    type: function
    ref: workflows.bank_to_ynab.steps.synthesize_transaction

  - name: push_to_ynab
    type: function
    ref: workflows.bank_to_ynab.steps.push_to_ynab

  - name: format_notifier_input
    type: function
    ref: workflows.bank_to_ynab.steps.format_notifier_input

  - name: telegram_notifier
    type: agent
    ref: workflows.bank_to_ynab.agents.telegram_notifier.create_telegram_notifier
